### ISSUE TITLE
Error: unable to register native methods

### ISSUE THREAD

**Issue by BartmanEH** [airsquared/blobsaver#129]
I'm back with issues with Java... again... I hate it, hate it, hate it.
After getting v2.3 to work with fixes issued in v2.3.1 for JavaFX detection, I'm back to trying v2.4.0 for iOS 13 blobs but getting an error "Error: unable to register native methods" when trying to "Read from connected device".

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App version v2.4.0

`java -version` output:
```
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) Client VM (build 25.241-b07, mixed mode)
```

**Log(s)**
```
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
```

**Comment by woxie** [comment]
I have the same issue (same OS, Java, and app version as well).

**Comment by Simon3748** [comment]
I have the same issue (same OS, Java, and app version as well)

**Comment by airsquared** [comment]
I have no idea why Windows keeps giving so many problems with Java (never had this issue on Mac/Linux), so I am working on a new way of distributing blobsaver that won't have any prerequisites (but I am attempting to use a new tool which doesn't have full Windows support, so it will take a while).

In the meantime, you can use the Linux version of blobsaver on Windows with WSL. There are multiple guides for using GUI Linux applications on Windows: 

- https://www.makeuseof.com/tag/linux-desktop-windows-subsystem/
- https://www.howtogeek.com/261575/how-to-run-graphical-linux-desktop-applications-from-windows-10s-bash-shell/

**Comment by BartmanEH** [comment]
Thanks for the suggestion but there is no way I’m gonna get into the mess of maintaining a java environment under Linux under Windows or polluting my Windows environment with all that xwindows stuff etc. I would run a full VM of Linux (or Mac, did I say that out loud?) instead. 

The workaround I’m using for now is manually entering the ID details of my devices (I recorded them from earlier versions of blobsaver) and snagging my blobs with the new version without auto detecting the connected device.

**Comment by airsquared** [comment]
Closing this issue as a duplicate of #81, please use that issue instead.
